apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-cpu-only
  labels:
    name: ubuntu-cpu-only
spec:
  nodeSelector:
    hardware-type: CPUONLY
   #For a server with GPUs
   #hardware-type: NVIDIAGPU 
  containers:
  - name:  ubuntu-cpu-only
    image: ubuntu
    command:
      - sleep
      - infinity
